name: CeeRoom
description: messenger application

publish_to: 'none'

version: 0.0.32+32

environment:
#  sdk: '>=2.18.1 <3.0.0'
  sdk: '>=3.4.3'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  page_transition: ^2.0.9
  dropdown_button2: ^2.1.3
  flutter_contacts: ^1.1.7+1
  shimmer: ^3.0.0
  get: ^4.6.5
  firebase_messaging: ^15.0.1
  firebase_core: ^3.1.0
  cloud_firestore: ^5.0.1
  cached_network_image: ^3.2.3
  get_storage: ^2.1.1
  url_launcher: ^6.1.11
  pin_input_text_field: ^4.5.0
  pinput: ^5.0.0
  flutter_callkit_incoming: ^2.0.3
  audioplayers: ^6.0.0
  #flutter_webrtc: ^0.9.48+hotfix.1
  flutter_webrtc: ^0.11.1
  animated_text_kit: ^4.2.2
  share_plus: ^9.0.0
  responsive_framework: 0.2.0
  web_socket_channel: ^3.0.0
  image_picker: ^1.0.7
  file_picker: ^8.0.0+1
  audio_waveforms: ^1.0.5
  dio: ^5.4.1
  open_file: ^3.3.2
  path_provider: ^2.1.2
  permission_handler: ^11.0.1
  uuid: ^4.2.2
  shared_preferences: ^2.2.2
  image_cropper: ^7.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/icons/
    - assets/images/flags/
    - assets/audios/

  fonts:
    - family: PoppinsLatin
      fonts:
        - asset: assets/fonts/PoppinsLatin-Regular.ttf
    - family: VazirmatnFA
      fonts:
       - asset: assets/fonts/Vazirmatn-FD-Regular.ttf